name = "espidf_netif"
description = "Ada/ESP-IDF NETIF bindings"
website = "https://github.com/godunko/espidf_netif"
version = "0.1.0-dev"
long-description = """
Ada bindings for the ESP-IDF Network Interface (NETIF) module, providing high-level networking support for Espressif microcontrollers.
"""

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["a0b", "embedded", "esp", "esp32", "espidf"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = true

[[depends-on]]
a0b_base = "*"
espidf = "*"
espidf_event = "*"
